### PR TITLE
Fix aligned allocation on Windows

### PR DESCRIPTION
**Pull request by nxrighthere**
Sorry, a bit messed with commits while decoupling it from my fork. The change itself is quite simple.

### CODE REVIEW

**Comment by WonderfulVoid** [comment]
I get what you are trying to do. For "reasons" (project doesn't have a contributor's agreement yet, my company will want that), I might create an equivalent patch myself.

**Comment by nxrighthere** [comment]
Sure, just pushed PR instead of an issue, seems easier. 😄

**Comment by WonderfulVoid** [comment]
Using x86_64-w64-mingw32-gcc as a Windows cross compiler on Linux, I get other warnings, e.g. when using "%lu" for uint64_t values. Seems uint64_t is "long long unsigned int" on Windows while it is "long unsigned int" on Linux. Long is only 32-bits on Windows/x86-64. This doesn't bother you?

I will make Progress64 build clean using x86_64-w64-mingw32-gcc and hope for the best when it comes to running.

**Comment by nxrighthere** [comment]
> This doesn't bother you?

Not really. There are many various platform-specific compilation errors, but I'm using the library only partially and fixed things on my side in no time. 😉 

> I will make Progress64 build clean using x86_64-w64-mingw32-gcc and hope for the best when it comes to running.

Sure, I'm ready to test it for ya.

**Comment by nxrighthere** [comment]
Forgot to mention that I'm using [MinGW-W64 GCC-8.1.0 x86_64-posix-seh](https://sourceforge.net/projects/mingw-w64/files/) on Windows.

**Comment by nxrighthere** [comment]
@WonderfulVoid Can you please add `p64_rwlock_r_try_acquire_wr()` for a one-shot attempt to acquire synchronizer which will return `true`/`false` instead of waiting? Just found a use-case for this and added it locally, but would like to see it here as well to verify that I implemented it right.

**Comment by WonderfulVoid** [comment]
Give me a couple of days. A bit busy at the moment.

Den ons 19 juni 2019 18:18NX <notifications@github.com> skrev:

**Comment by WonderfulVoid** [comment]
Everything except the benchmarks now builds cleanly for Windows (x86-64) now. The benchmarks requires pthreads and other Linux kernel API's, too much work for too little value in porting that to Windows.

**Comment by WonderfulVoid** [comment]
Also implemented try_acquire_rd() and try_acquire_wr() for for rwlock and rwlock_r.
Have you considered the task fair (tfrw) and phase fair (pfrw) read/write locks?

**Comment by nxrighthere** [comment]
Awesome, thanks!

> Have you considered the task fair (tfrw) and phase fair (pfrw) read/write locks?

Yes it looks interesting, but the problem is that in my library a user can make recursive calls which will lead to a deadlock unfortunately (or it doesn't suffer this?).

**Comment by nxrighthere** [comment]
By the way, it seems that some comments in the phase fair implementation are related to the task fair: _Initialise a task fair reader/writer lock_.

**Comment by WonderfulVoid** [comment]
Good catch! I will fix that comment in p64_pfrwlock.h.

No, tfrw and pfrw locks don't support recursion but I can create recursive versions of them as well. Maybe emulate some kind of template support where the user can specify which underlying (non-recursive) lock implementation to use.

tfrw is as fast or faster than the basic rwlock (measured on both 8-core Skylake and some ARM targets) but is also fair which means it will avoid starvation.

**Comment by nxrighthere** [comment]
Whoa, sounds really promising! If it's possible to add support for recursion, I definitely would like to give it a try!

**Comment by nxrighthere** [comment]
@WonderfulVoid Any progress on recursion support for TFRW lock? 😋

**Comment by WonderfulVoid** [comment]
Sorry forgot. Do you need the trylock versions as well? The task-fair R/W
lock currently doesn't implement those but I am sure I can implement them.

Den tis 8 okt. 2019 kl 15:42 skrev NX <notifications@github.com>:

**Comment by nxrighthere** [comment]
Nope, _try_ is not required, only support for recursion is very important, thanks!

By the way, found this repository randomly https://github.com/yohhoy/yamc, seems quite interesting but it's for C++ unfortunately.

**Comment by nxrighthere** [comment]
Ticket lock is also looks interesting, dunno if it's better than just exclusive write operations with TFRW. 🤔

**Comment by nxrighthere** [comment]
Also, thinking about eventual fairness to ensure that the lock will be fair on average similar to https://docs.rs/parking_lot/0.7.1/parking_lot/type.Mutex.html

**Comment by WonderfulVoid** [comment]
Recursive tfrw lock:
https://github.com/ARM-software/progress64/commit/ac67384edb947a59b0d717290d6375897c0fa007

I will take a look at the links you provided.

**Comment by WonderfulVoid** [comment]
You can use bm_lock to check how fair a lock implementation is on your specific platform. Fairness is computed using the geometric mean.
```
$ ./bm_lock 
Usage: bm_lock [<options>] <locktype>
-a <binmask>     CPU affinity mask (default base 2)
-f <megahz>      CPU frequency in MHz
-c               Perform lock checks
-l <numlaps>     Number of laps
-o <numobjs>     Number of objects (locks)
-t <numthr>      Number of threads
-v               Verbose
Lock types: plain rw tfrw pfrw clh rwclh tkt sem rwsync
$ ./bm_lock -t4 plain
2 plain spin locks, 1000000 laps, 4 threads, affinity mask=0xffffffff
0: numops 990129
1: numops 978279
2: numops 1000000
3: numops 998858
Duration: 1.3465 seconds
Fairness: 0.991778
2946174 lock ops/second, 339 nanoseconds/lock op
```

**Comment by nxrighthere** [comment]
Thank you for this!

Got these numbers on AMD FX-4300:
```
~/progress64$ ./bm_lock -t4 plain
2 plain spin locks, 1000000 laps, 4 threads, affinity mask=0xffffffff
0: numops 986155
1: numops 991009
2: numops 1000000
3: numops 988002
Duration: 0.5444 seconds
Fairness: 0.991277
7282320 lock ops/second, 137 nanoseconds/lock op
```

**Comment by WonderfulVoid** [comment]
You probably want to measure fairness with only one lock. This seems to better expose unfairness (in the lock design and in the hardware).
./bm_lock -o1 -t4 plain

**Comment by nxrighthere** [comment]
With only one:
```
~/progress64$ ./bm_lock -o1 -t4 plain
1 plain spin lock, 1000000 laps, 4 threads, affinity mask=0xffffffff
0: numops 964378
1: numops 975963
2: numops 982340
3: numops 1000000
Duration: 0.9945 seconds
Fairness: 0.980586
3943991 lock ops/second, 253 nanoseconds/lock op
```

**Comment by nxrighthere** [comment]
@WonderfulVoid The TFRW works just great! I see noticeable better framerate consistency over unfair RW in my application. Thanks!

**Comment by WonderfulVoid** [comment]
Great! Good to know that these academic exercises actually provide benefit to real applications.
Maybe you should also try the phase-fair RW lock, it is supposed to be even better for real-time applications. I guess I will have to create a recursive version of it.

**Comment by nxrighthere** [comment]
Yea, maybe phase fairness would be better since I have at least two read operations called one after another on the hot path. 🤔

**Comment by WonderfulVoid** [comment]
Just do a search and replace s/tfrw/pfrw/g in p64_tfrwlock_r.[ch] and you should have a recursive pfrw lock.

**Comment by WonderfulVoid** [comment]
Please inform of the results of using the phase-fair lock. Does it indeed improve determinism from an application perspective?
The pfrw lock will still allow consecutive read operations to overlap, as long as there is no intermediate write operation. I assume this is desired or else you would not use any kind of reader/writer lock.
The pfrw design & implementation is my own, inspired by but not identical to the Brandenburg-Anderson design. I hope I didn't screw up.
There are other fair (FCFS) lock designs, e.g. CLH and RWCLH - my reader/writer flavour of CLH. CLH is pretty good when there are a lot of contenting threads.

**Comment by nxrighthere** [comment]
I have only two threads currently (probably will be more). The main thread and network thread. The main thread is a game loop essentially, where 90% of the time only read operations are executed while in the network thread, all operations are exclusive.

Gonna try phase-fair implementation soon and let you know how it works. 👌

**Comment by WonderfulVoid** [comment]
With only two threads, I doubt PFRW lock will make any difference over TFRW lock. I think you would need more threads in order to have situations where the PFRW lock behave differently TFRW.

Ticket lock is fair (FCFS - first come first serve) but doesn't allow multiple concurrent readers. The task fair RW lock is essentially a ticket lock with support for multiple concurrent readers. If you only used writer locks with TFRW, it would become a ticket lock, potentially with slightly higher overhead (needs to do CAS instead of a simpler atomic-fetch-add), at least on x86.

**Comment by nxrighthere** [comment]
Thanks for the info, will stick with TFRW for now then. In the worst case, I might end up with 2 concurrent readers, but most of the time, there will be only one writer. I'm actually quite happy with TFRW for now, guaranteed fairness is instantly noticeable with continuous concurrent function calls between two threads. 👍

**Pull request closed without merging**
